
GET http://localhost:3000/reviews
###

GET http://localhost:3000/reviews/metadata
###

PUT http://localhost:3000/reviews/helpful
###



POST http://localhost:3000/reviews/addProductIds

####
POST http://localhost:3000/reviews/addReview

####
POST http://localhost:3000/reviews/addPhotos

####
POST http://localhost:3000/reviews/addCharacteristics

####
POST http://localhost:3000/reviews/addCharNames